packages:
  - backend
  - frontend
  - common
  - docs
  - tests

onlyBuiltDependencies:
  - "@clerk/shared"
  - "@datadog/native-appsec"
  - "@datadog/native-iast-taint-tracking"
  - "@datadog/native-metrics"
  - "@datadog/pprof"
  - "@scarf/scarf"
  - bcrypt
  - dd-trace
  - esbuild
  - msgpackr-extract
  - sharp
  - tesseract.js
  - unrs-resolver
