"use client";

import { enUS, nb } from "date-fns/locale";
import { useLanguage, type Language } from "@/app/i18n";

export type CanvasVisning = "announcements" | "courses" | "assignments";

export function getCanvasLabels(language: Language) {
    if (language === "en") {
        return {
            sectionTitles: {
                announcements: "Announcements",
                courses: "Courses",
                assignments: "Assignments",
            } satisfies Record<CanvasVisning, string>,
            announcementsLoading: "Loading announcements...",
            announcementsLoadError: "Could not load announcements. Try again.",
            announcementsEmpty: "No announcements",
            loadMoreAnnouncements: (count: number) => `Load more announcements (${count} left)`,
            coursesLoadError: "Could not load courses. Try again.",
            backToCourses: "Back to courses",
            goBack: "Go back",
            backToModules: "Back to modules",
            frontPage: "Front page",
            modules: "Modules",
            pages: "Pages",
            files: "Files",
            courseAnnouncements: "Announcements",
            published: "Published",
            pageLoading: "Loading page...",
            pageLoadError: "Could not load the page. Try again.",
            courseAnnouncementsLoading: "Loading announcements...",
            courseAnnouncementsError: "Could not load announcements. Try again.",
            courseAnnouncementsEmpty: "No announcements for this course.",
            frontPageLoading: "Loading front page...",
            frontPageLoadError: "Could not load front page. Try again.",
            frontPageEmpty: "No content on the front page.",
            frontPageUnavailable: "Front page unavailable.",
            modulesLoading: "Loading modules...",
            modulesAccessError: "No access to modules for this course (403/unauthorized).",
            modulesEmpty: "This course has no available modules.",
            moduleLabel: "Module",
            courseLabel: "Course",
            contentLabel: "Content",
            noItems: "No items.",
            openFileErrorTitle: "Could not open file",
            openFileErrorDescription: "Canvas did not return a valid download link for this file.",
            retrySoon: "Try again shortly.",
            pagesLoading: "Loading pages...",
            pagesAccessError: "This course has no pages or you do not have access (403/unauthorized).",
            pagesEmpty: "This course has no available pages.",
            pagesNothingToShow: "This course has no pages to show.",
            filesLoading: "Loading files...",
            filesAccessError: "This course has no files or you do not have access (403/unauthorized).",
            filesEmpty: "This course has no available files.",
            filesNothingToShow: "This course has no files to show.",
            noCourses: "No courses found",
            noContent: "No content",
            openCourse: "Open course",
            assignmentsLoading: "Loading assignments...",
            assignmentsLoadError: "Could not load assignments. Try again.",
            assignmentsEmptyTitle: "No assignments found.",
            assignmentsEmptyDescription: "When you have active assignments in your Canvas courses, they will appear here.",
            showingAssignments: (filtered: number, total: number) => `Showing ${filtered} of ${total} assignments`,
            assignmentFilters: {
                alle: "All",
                kommende: "Upcoming",
                forfalt: "Overdue",
                "uten-frist": "No due date",
            } as Record<"alle" | "kommende" | "forfalt" | "uten-frist", string>,
            sortByDue: "Sorted by due date",
            sortByCourse: "Sorted by course",
            assignmentCourse: "Course",
            submitted: "Submitted",
            manuallySubmitted: "Manually submitted",
            markAsSubmitted: "Mark as submitted",
            unmarkAsSubmitted: "Unmark as submitted",
            points: "Points",
            due: "Due",
            pointsSuffix: "points",
            noDueDate: "No due date",
            showLessAssignments: "Show fewer assignments",
            showAllAssignments: (count: number) => `Show all ${count} assignments`,
        };
    }

    return {
        sectionTitles: {
            announcements: "Kunngjøringer",
            courses: "Emner",
            assignments: "Oppgaver",
        } satisfies Record<CanvasVisning, string>,
        announcementsLoading: "Laster kunngjøringer...",
        announcementsLoadError: "Kunne ikke laste kunngjøringer. Prøv igjen.",
        announcementsEmpty: "Ingen kunngjøringer",
        loadMoreAnnouncements: (count: number) => `Hent flere kunngjøringer (${count} igjen)`,
        coursesLoadError: "Kunne ikke laste emner. Prøv igjen.",
        backToCourses: "Tilbake til emner",
        goBack: "Gå tilbake",
        backToModules: "Tilbake til moduler",
        frontPage: "Forside",
        modules: "Moduler",
        pages: "Sider",
        files: "Filer",
        courseAnnouncements: "Kunngjøringer",
        published: "Publisert",
        pageLoading: "Laster siden...",
        pageLoadError: "Kunne ikke laste siden. Prøv igjen.",
        courseAnnouncementsLoading: "Laster kunngjøringer...",
        courseAnnouncementsError: "Kunne ikke laste kunngjøringer. Prøv igjen.",
        courseAnnouncementsEmpty: "Ingen kunngjøringer for dette emnet.",
        frontPageLoading: "Laster forside...",
        frontPageLoadError: "Kunne ikke laste forside. Prøv igjen.",
        frontPageEmpty: "Ingen innhold på forsiden.",
        frontPageUnavailable: "Forside ikke tilgjengelig.",
        modulesLoading: "Laster moduler...",
        modulesAccessError: "Ingen tilgang til moduler for dette emnet (403/unauthorized).",
        modulesEmpty: "Dette emnet har ingen moduler tilgjengelig.",
        moduleLabel: "Modul",
        courseLabel: "Emne",
        contentLabel: "Innhold",
        noItems: "Ingen punkter.",
        openFileErrorTitle: "Kunne ikke åpne fil",
        openFileErrorDescription: "Canvas returnerte ingen gyldig nedlastingslenke for denne filen.",
        retrySoon: "Prøv igjen om litt.",
        pagesLoading: "Laster sider...",
        pagesAccessError: "Dette emnet har ingen sider eller du mangler tilgang (403/unauthorized).",
        pagesEmpty: "Dette emnet har ingen sider tilgjengelig.",
        pagesNothingToShow: "Dette emnet har ingen sider å vise.",
        filesLoading: "Laster filer...",
        filesAccessError: "Dette emnet har ingen filer eller du mangler tilgang (403/unauthorized).",
        filesEmpty: "Dette emnet har ingen filer tilgjengelig.",
        filesNothingToShow: "Dette emnet har ingen filer å vise.",
        noCourses: "Ingen emner funnet",
        noContent: "Ingen innhold",
        openCourse: "Åpne emne",
        assignmentsLoading: "Laster oppgaver...",
        assignmentsLoadError: "Kunne ikke laste oppgaver. Prøv igjen.",
        assignmentsEmptyTitle: "Ingen oppgaver funnet.",
        assignmentsEmptyDescription: "Når du har aktive oppgaver i Canvas-emnene dine, dukker de opp her.",
        showingAssignments: (filtered: number, total: number) => `Viser ${filtered} av ${total} oppgaver`,
        assignmentFilters: {
            alle: "Alle",
            kommende: "Kommende",
            forfalt: "Forfalt",
            "uten-frist": "Uten frist",
        } as Record<"alle" | "kommende" | "forfalt" | "uten-frist", string>,
        sortByDue: "Sortert etter frist",
        sortByCourse: "Sortert etter emne",
        assignmentCourse: "Emne",
        submitted: "Innlevert",
        manuallySubmitted: "Manuelt innlevert",
        markAsSubmitted: "Marker som innlevert",
        unmarkAsSubmitted: "Fjern innlevert-markering",
        points: "Poeng",
        due: "Frist",
        pointsSuffix: "poeng",
        noDueDate: "Ingen frist",
        showLessAssignments: "Vis færre oppgaver",
        showAllAssignments: (count: number) => `Vis alle ${count} oppgaver`,
    };
}

export type CanvasLabels = ReturnType<typeof getCanvasLabels>;

export function useCanvasLabels() {
    const { language } = useLanguage();

    return {
        language,
        labels: getCanvasLabels(language),
        dateLocale: language === "en" ? enUS : nb,
    };
}
